CREATE TABLE `users`(
   `id` INTEGER PRIMARY KEY AUTOINCREMENT,
   `username` VARCHAR(32) NOT NULL,
   `passwd` VARCHAR(32) NOT NULL,
   `name` VARCHAR(32) NOT NULL,
   `age` INTEGER NOT NULL,
   `sex` INTEGER NOT NULL,
   `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO "users" VALUES(1,'maomao','110110','茅云龙',30,1,'2016-04-27 04:10:41');
CREATE TABLE `finances`(
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `user_id` INTEGER NOT NULL,
  `type` INTEGER NOT NULL,
  `amount` FLOAT(2,9) NOT NULL,
  `comments` VARCHAR(256),
  `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id)
);
